### PR TITLE
Added an "&& exit" to ssh command

### PR DESCRIPTION
**Pull request by michaaa**
Maybe it's a good idea to automatically close the corresponding pane after ssh disconnects?

### CODE REVIEW

**Comment by hukl** [comment]
sounds good - will test it

**Comment by hukl** [comment]
actually I prefer to keep the pane open and see the reason for the connection being closed. Could be maybe an option in the script rather than the default

**Comment by michaaa** [comment]
However, because of the "&&" the return code of the ssh session has to be 0 to trigger the exit. If something went wrong (ssh exits with something else than 0), you'll be able to see the reason 'cause the exit won't trigger in that case.

**Comment by hukl** [comment]
ah now I see what you mean. I'm always ending the whole session with a separate key binding which is why I never needed that behavior. Will give it some more thought! :)

**Comment by michaaa** [comment]
Sometimes I only want to close one pane (cause I accidentally opend it, or the server is already "done", whatever...) :)

However, maybe I implement the "exit"-feature as a command line switch later...

**Comment by michaaa** [comment]
Now the "auto exit" feature is an optional switch for those who like it... :)

**Pull request merged**
