### PR TITLE
Add support for a remote jumphost to reach server clusters in a secured area.

### PR DESCRIPTION
**Pull request by ColdSphinX**

### CODE REVIEW

**Comment by hukl** [comment]
man page needs an update too ;)

**Comment by ColdSphinX** [comment]
What a mess, but I think I got it now...
mandoc and manual file updated.
Also included the 2 pullrequests for checking "if in tmux session" and optional "&& exit" as it had to be changed to stay compatible with my changes.

**Comment by appusidharthan** [comment]
Is this feature is rolling out anytime soon ?

**Comment by hukl** [comment]
If you could test this version and let me know if it works well, I'd be willing to merge it in :)

**Comment by hukl** [comment]
Although it is currently conflicting - I might get to it on the weekend

**Comment by hukl** [comment]
Actually decided not to merge because you can get this done by specifying the `-o` option and pass your jumphost config this way :D

**Pull request closed without merging**
