### PR TITLE
Feature pane title

### PR DESCRIPTION
**Pull request by elcorto**
Hi

I did some work regarding identification of panes -- name each pane by the host we are connected to. I added two options -p (set tmux' pane_title, see new README section about that) and -P (set PS1 prompt as brute-force method). 

Additionally, there is now -S (switch on pane syncing). 

Added a Makefile for the man page and removed the generated man/hostmux.1 from the repo since it is machine-generated from revision-controlled hostmux.mandoc .

cheers,
elcorto

### CODE REVIEW

**Comment by hukl** [comment]
I'd prefer another option flag for synchronization - maybe -a ? I don't fancy uppercase/lowercase options that do completely different things

**Comment by hukl** [comment]
Also I actually don't mind having the commands in my shell history and I often use them in a ctrl-r kind of fashion. Pull requests should be single features / changes and not many at once because then it is rather hard to argue about individual things. Either way - An extra flag to control that behaviour might be desirable.

**Comment by elcorto** [comment]
Rename -S option to avoid confusion with -s: good point

Shell history: Well actually I don't mind having that in the history, either. I included it since you merged https://github.com/hukl/hostmux/commit/63c37d62a0310e0f345512102b3f483207a148ba .

An extra flag: you mean the history thing? I'd say it's not worth a flag and one should stick with one default behavior.

Multiple features in PR: I could squash and split into a single commit per feature, close this PR, force-push the new commits and issue a new PR per feature?

**Comment by hukl** [comment]
well no - now it would be too much hassle. Just a remark for future pull requests :)

**Comment by elcorto** [comment]
Will do it anyway :) Closing this PR.

**Comment by hukl** [comment]
oookay :)

**Pull request closed without merging**
